---
- name: Setup server
  hosts: local
  user: vagrant
  sudo: yes
  tasks:
#  - name: Install GUI related packages
#    yum:
#      state: present
#      name: 
#        - '@gnome desktop'
#        - xorg*
#  - name: Remove GUI related packages
#    yum:
#      state: absent
#      name:
#        - initial-setup
#        - initial-setup-gui
#  - name: Switch to the GUI target
#    shell: sh /vagrant/scripts/setup-centos-gui.sh
  - name: Install LAMP packages
    yum:
      state: present
      name:
        - httpd
        - mariadb-server
        - mariadb
        - php
        - php-mysql
  - name: ensure httpd is running
    service:
      name: httpd
      state: started
  - name: Copy hello world php file
    copy:
      src: /vagrant/files/hello_world.php
      dest: /tmp/hello_world.php
  - name: Install expect command
    yum:
      name: expect
      state: present
#  - name: Run mysql secure installation script
#    shell: /usr/bin/sh /vagrant/scripts/mysql_secure_installation.sh
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted      
